#!/usr/bin/env ruby

require 'json'

library_code = 'function createContract(abiDefinition) {  return web3.eth.contract(abiDefinition);}function deployContract(contract, input, account, code, gas) {  var instance = contract.new(input,{from:account, data: code, gas: gas}, function (e, contract) {  if(!e) {    if(!contract.address) {      console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");    } else {      console.log("Contract mined! Address: " + contract.address);      console.log(contract);    }  } else {    console.log(e)  }  });  return instance;}
'
file_name = ARGV[0]
code = File.read(file_name).gsub("\n",'')

json_string= `curl -s -X POST --data '{"jsonrpc":"2.0","method":"eth_compileSolidity","params":["#{code}"],"id":1}' http://127.0.0.1:8100`

json_object = JSON.parse(json_string)
compiled_object = json_object['result'].to_json
javascript_file_name = file_name.split('.')[0] + '_compiled.js'

File.open(javascript_file_name, 'w') do |f|
  f.write("#{library_code};\nvar compiled = #{compiled_object};")
end
puts "loadScript('#{`pwd`}/#{javascript_file_name}')".gsub("\n",'')
